import { useState, type Dispatch } from 'react';
import { clockText, status, type Action, type Capabilities, type SpaState } from './model';
const coverage = [
  ['Home, dial e indicadores','3, 7','Documentado','Distribución e indicadores; iconos reconstruidos en SVG.'],
  ['Gestos y navegación','4, 5','Documentado','Arrastre con mouse y táctil, listas y acceso a Settings, Spa y Music.'],
  ['Hora y mensaje 40','6','Documentado','Hora 12/24 h, guardar/cancelar y aviso hasta configurar.'],
  ['Temperatura','7, 11','Documentado','Consigna, rangos, dial, rojo al calentar; un minuto de circulación para medir.'],
  ['Equipos y Priming','8','Mixto','Máximo seis equipos por página; velocidades configurables. Salida de Priming manual.'],
  ['Filtración','9','Mixto','Dos ciclos; ciclo 2 opcional. Inicio igual a fin se interpreta como 24 horas.'],
  ['General e idioma','10','Mixto','Opciones documentadas; español es traducción propia y los recordatorios son escenarios demo.'],
  ['Ready / Rest y M8','11','Mixto','Ready/Rest según manual. M8 aproxima muestreo: 30 min, o 60 min con agua estable.'],
  ['Suspensión','12','Mixto','Secuencia 1 → 2 documentada. Tap to Wake directo y lista de tiempos ampliada son aproximaciones.'],
  ['Audio / bba 3','3, 4, 5, 13','Aproximado','Controles, pistas y progreso simulados, sin reproducir ni descargar grabaciones.'],
  ['Chromazone y Light Cycles','4, 5, 8, 13','Aproximado','Color, intensidad y un horario diario. No hay capturas de estos controles.'],
  ['Clim8zone / Clim8zone II','5, 13','Aproximado','Off / Heat / Auto. Auto coopera con la demanda de calor; no añade refrigeración no documentada.'],
  ['Connections','3, 5','Aproximado','Estados Offline / Local / Cloud, sin Bluetooth ni servicios externos.'],
  ['Hold / Cleanup Cycle','3, 5','Aproximado','Hold de 60 min detiene equipos. Limpieza programable tras 30 min sin uso manual.'],
  ['Security','3, 5','Aproximado','Bloqueos de panel/ajustes; desbloqueo demo 1 → 2, no contraseña de un equipo real.'],
  ['Diagnostics','4, 5','Mixto','Campos visibles en la captura; voltaje y software ilustrativos, temperaturas derivadas del motor.'],
  ['Software Update / About','3, 5','Aproximado','Actualización demo de 10 segundos del reloj simulado; nunca cambia la revisión de referencia.'],
];
export function SimulatorTools({s,dispatch,speed,setSpeed,paused,setPaused,reset,wake,navigate}:{s:SpaState;dispatch:Dispatch<Action>;speed:number;setSpeed:(n:number)=>void;paused:boolean;setPaused:(b:boolean)=>void;reset:()=>void;wake:()=>void;navigate:(to:string)=>void}) {
  const st=status(s);const [confirm,setConfirm]=useState(false);const cap=s.settings.capabilities;
  const setCap=(patch:Partial<Capabilities>)=>{dispatch({type:'settings',patch:{capabilities:{...cap,...patch}}});dispatch({type:'state',patch:{manualPumps:Array(8).fill(0),blowerOn:false,playing:patch.audio===false?false:s.playing}});navigate('home');};
  return <section className="tools-area"><details className="sim-tools"><summary><span className="summary-icon">⌘</span><span>Simulación <small>Tiempo, equipos y escenarios</small></span><span className="summary-status">{paused?'En pausa':`${speed}×`} <span className={st.heating?'warm-dot':'cool-dot'}/> {st.heating?'Calentando':'En espera'}</span></summary>
    <div className="tools-content"><div className="tools-grid">
      <section><h3>Reloj del spa</h3><div className="clock-readout">{clockText(s.clock,true)}<small>día {Math.floor(s.clock/86400)+1}</small></div><div className="tool-buttons"><button onClick={()=>setPaused(!paused)}>{paused?'▶ Continuar':'Ⅱ Pausar'}</button>{[1,10,60].map(n=><button key={n} aria-pressed={speed===n} onClick={()=>setSpeed(n)}>{n}×</button>)}</div><div className="tool-buttons"><button onClick={()=>dispatch({type:'tick',seconds:60})}>+1 min</button><button onClick={()=>dispatch({type:'tick',seconds:900})}>+15 min</button><button onClick={()=>dispatch({type:'tick',seconds:3600})}>+1 hora</button></div><p className="tool-note">La suspensión usa tiempo real, incluso con el reloj pausado.</p></section>
      <section><h3>Agua y estado</h3><label className="tool-field">Temperatura del agua <span>{s.waterC.toFixed(1)} °C</span><input type="range" aria-label="Simulated water temperature" min={10} max={42} step={.5} value={s.waterC} onChange={e=>dispatch({type:'state',patch:{waterC:Number(e.target.value)}})}/></label><div className="state-badges"><span className={st.flow?'on':''}>Flujo {st.flow?'ON':'OFF'}</span><span className={st.heating?'on':''}>Calor {st.heating?'ON':'OFF'}</span><span className={st.filterIds.length?'on':''}>Filtro {st.filterIds.join('+')||'OFF'}</span><span>{s.priming?'Priming':s.startup?'Midiendo…':st.validTemperature?'Lectura válida':'Lectura caducada'}</span></div><div className="tool-buttons"><button onClick={()=>{dispatch({type:'prime',on:!s.priming});wake();navigate('spa');}}>{s.priming?'Finalizar Priming':'Iniciar Priming'}</button><button onClick={()=>dispatch({type:'state',patch:{startup:false,lastSample:s.clock-3601,sampledC:null,sampleSeconds:0}})}>Caducar lectura</button></div></section>
      <section><h3>Configuración del spa</h3><label className="tool-select">Bombas<select aria-label="Number of pumps" value={cap.pumps} onChange={e=>setCap({pumps:Number(e.target.value)})}>{Array.from({length:8},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label><label className="tool-select">Velocidades<select aria-label="Pump speeds" value={cap.speeds} onChange={e=>setCap({speeds:Number(e.target.value) as 1|2})}><option value={1}>Una</option><option value={2}>Dos</option></select></label><div className="capabilities">{([['blower','Blower'],['circulation','Circulación'],['audio','Audio bba 3'],['chromazone','Chromazone'],['clim8zone','Clim8zone'],['ozone','Ozono'],['m8','M8']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={cap[key]} onChange={e=>setCap({[key]:e.target.checked})}/>{label}</label>)}</div></section>
      <section><h3>Escenarios</h3><label className="tool-select">Conexión<select aria-label="Simulated connection" value={s.connection} onChange={e=>dispatch({type:'state',patch:{connection:e.target.value as SpaState['connection']}})}><option>Offline</option><option>Local</option><option>Cloud</option></select></label><div className="tool-buttons wrap"><button onClick={()=>{dispatch({type:'settings',patch:{reminders:true}});dispatch({type:'state',patch:{reminderDismissed:false}});wake();navigate('messages');}}>Mostrar recordatorio</button><button onClick={wake}>Despertar pantalla</button><button onClick={()=>{dispatch({type:'settings',patch:{panelLocked:false,settingsLocked:false}});wake();}}>Quitar bloqueos</button></div><div className="reset-area">{confirm?<><span>¿Borrar ajustes guardados?</span><button onClick={()=>{reset();setConfirm(false);}}>Sí, restablecer</button><button onClick={()=>setConfirm(false)}>Cancelar</button></>:<button onClick={()=>setConfirm(true)}>Restablecer simulador</button>}</div></section>
    </div></div>
  </details>
  <details className="coverage"><summary><span>Referencia y alcance</span><span>42410 Rev. A ↗</span></summary><div className="coverage-body"><h3>Una revisión, una referencia.</h3><p>La interfaz se basa exclusivamente en el PDF suministrado, <strong>Spa Touch 4 User Guide · MVP Release · No. 42410 Rev. A</strong>. Las opciones que el documento menciona sin describir se completaron como simulaciones; no representan pantallas verificadas del firmware.</p><p>Modelo térmico ilustrativo: calentador a 2 °C/h, o 4 °C/h con Clim8zone; pérdida proporcional hacia un ambiente de 22 °C. No calcula consumo ni predice el comportamiento de un spa real. Los ajustes se guardan en este navegador; los equipos, conexiones y lecturas se reinician al recargar.</p><div className="coverage-table"><table><thead><tr><th>Función</th><th>Página</th><th>Fidelidad</th><th>Detalle</th></tr></thead><tbody>{coverage.map(([name,page,level,detail])=><tr key={name}><td>{name}</td><td>{page}</td><td><span className={`fidelity ${level==='Documentado'?'documented':''}`}>{level}</span></td><td>{detail}</td></tr>)}</tbody></table></div><p className="tool-note">La pista “White Christmas / Bing Crosby” reproduce únicamente los metadatos visibles en la página 3. No incluye audio ni conexión a servicios de música.</p></div></details>
  </section>;
}
