import { useState, type Dispatch } from 'react';
import { clockText, status, type Action, type Capabilities, type SpaState } from './model';
const coverage = [
  ['Home, dial and indicators','3, 7','Documented','Layout and status indicators; icons recreated in SVG.'],
  ['Gestures and navigation','4, 5','Documented','Mouse and touch dragging, scrolling lists, and access to Settings and Spa.'],
  ['Time and message 40','6','Documented','12/24-hour time, save/cancel controls, and a reminder until the time is set.'],
  ['Temperature','7, 11','Documented','Set point, ranges, dial and red heating indicator; one minute of circulation before a reading.'],
  ['Devices and Priming','8','Mixed','Requested profile: two single-speed pumps, circulation and a light. Priming is ended manually.'],
  ['Filtration','9','Mixed','Two cycles; cycle 2 is optional. Matching start and end times mean a 24-hour cycle.'],
  ['General and language','10','Mixed','Documented options; Spanish is a custom translation and reminders are demo scenarios.'],
  ['Ready / Rest and M8','11','Mixed','Ready/Rest follow the guide. M8 sampling is approximated: 30 minutes, or 60 when water temperature is stable.'],
  ['Sleep','12','Mixed','The 1 → 2 sequence is documented. Direct Tap to Wake and the extended timeout list are approximations.'],
  ['Audio / bba 3','3, 4, 5, 13','Omitted','Music player and audio controls removed from this simulator by request.'],
  ['Chromazone and Light Cycles','4, 5, 8, 13','Approximate','Color, brightness and one daily schedule. The guide does not show these controls.'],
  ['Clim8zone / Clim8zone II','5, 13','Approximate','Off / Heat / Auto. Auto responds to heat demand; undocumented cooling behavior is not added.'],
  ['Connections','3, 5','Approximate','Offline / Local / Cloud states, without Bluetooth or external services.'],
  ['Hold / Cleanup Cycle','3, 5','Approximate','A 60-minute Hold stops devices. Configurable cleanup starts 30 minutes after manual use ends.'],
  ['Security','3, 5','Approximate','Panel/settings locks; demo 1 → 2 unlock sequence, not a real device password.'],
  ['Diagnostics','4, 5','Mixed','Fields shown in the screenshot; illustrative voltage and software values, with temperatures from the simulation engine.'],
  ['Software Update / About','3, 5','Approximate','A 10-second demo update using the simulation clock; the reference revision never changes.'],
];
export function SimulatorTools({s,dispatch,speed,setSpeed,paused,setPaused,reset,wake,navigate}:{s:SpaState;dispatch:Dispatch<Action>;speed:number;setSpeed:(n:number)=>void;paused:boolean;setPaused:(b:boolean)=>void;reset:()=>void;wake:()=>void;navigate:(to:string)=>void}) {
  const st=status(s);const [confirm,setConfirm]=useState(false);const cap=s.settings.capabilities;
  const setCap=(patch:Partial<Capabilities>)=>{dispatch({type:'settings',patch:{capabilities:{...cap,...patch}}});dispatch({type:'state',patch:{manualPumps:[0,0],blowerOn:false}});navigate('home');};
  return <section className="tools-area"><details className="sim-tools"><summary><span className="summary-icon">⌘</span><span>Simulation <small>Time, devices and scenarios</small></span><span className="summary-status">{paused?'Paused':`${speed}×`} <span className={st.heating?'warm-dot':'cool-dot'}/> {st.heating?'Heating':'Idle'}</span></summary>
    <div className="tools-content"><div className="tools-grid">
      <section><h3>Spa clock</h3><div className="clock-readout">{clockText(s.clock,true)}<small>day {Math.floor(s.clock/86400)+1}</small></div><div className="tool-buttons"><button onClick={()=>setPaused(!paused)}>{paused?'▶ Resume':'Ⅱ Pause'}</button>{[1,10,60].map(n=><button key={n} aria-pressed={speed===n} onClick={()=>setSpeed(n)}>{n}×</button>)}</div><div className="tool-buttons"><button onClick={()=>dispatch({type:'tick',seconds:60})}>+1 min</button><button onClick={()=>dispatch({type:'tick',seconds:900})}>+15 min</button><button onClick={()=>dispatch({type:'tick',seconds:3600})}>+1 hour</button></div><p className="tool-note">Screen sleep uses real time, even when the simulation clock is paused.</p></section>
      <section><h3>Water and status</h3><label className="tool-field">Water temperature <span>{s.waterC.toFixed(1)} °C</span><input type="range" aria-label="Simulated water temperature" min={10} max={42} step={.5} value={s.waterC} onChange={e=>dispatch({type:'state',patch:{waterC:Number(e.target.value)}})}/></label><div className="state-badges"><span className={st.flow?'on':''}>Flow {st.flow?'ON':'OFF'}</span><span className={st.heating?'on':''}>Heat {st.heating?'ON':'OFF'}</span><span className={st.filterIds.length?'on':''}>Filter {st.filterIds.join('+')||'OFF'}</span><span>{s.priming?'Priming':s.startup?'Measuring…':st.validTemperature?'Valid reading':'Stale reading'}</span></div><div className="tool-buttons"><button onClick={()=>{dispatch({type:'prime',on:!s.priming});wake();navigate('spa');}}>{s.priming?'End Priming':'Start Priming'}</button><button onClick={()=>dispatch({type:'state',patch:{startup:false,lastSample:s.clock-3601,sampledC:null,sampleSeconds:0}})}>Expire reading</button></div></section>
      <section><h3>Spa configuration</h3><p className="tool-note">2 single-speed pumps · Circulation · Lights</p><div className="capabilities">{([['chromazone','Chromazone'],['clim8zone','Clim8zone'],['ozone','Ozone'],['m8','M8']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={cap[key]} onChange={e=>setCap({[key]:e.target.checked})}/>{label}</label>)}</div></section>
      <section><h3>Scenarios</h3><label className="tool-select">Connection<select aria-label="Simulated connection" value={s.connection} onChange={e=>dispatch({type:'state',patch:{connection:e.target.value as SpaState['connection']}})}><option>Offline</option><option>Local</option><option>Cloud</option></select></label><div className="tool-buttons wrap"><button onClick={()=>{dispatch({type:'settings',patch:{reminders:true}});dispatch({type:'state',patch:{reminderDismissed:false}});wake();navigate('messages');}}>Show reminder</button><button onClick={wake}>Wake screen</button><button onClick={()=>{dispatch({type:'settings',patch:{panelLocked:false,settingsLocked:false}});wake();}}>Clear locks</button></div><div className="reset-area">{confirm?<><span>Clear saved settings?</span><button onClick={()=>{reset();setConfirm(false);}}>Yes, reset</button><button onClick={()=>setConfirm(false)}>Cancel</button></>:<button onClick={()=>setConfirm(true)}>Reset simulator</button>}</div></section>
    </div></div>
  </details>
  <details className="coverage"><summary><span>Reference and scope</span><span>42410 Rev. A ↗</span></summary><div className="coverage-body"><h3>One revision, one reference.</h3><p>The interface is based exclusively on the supplied PDF, <strong>Spa Touch 4 User Guide · MVP Release · No. 42410 Rev. A</strong>. Features mentioned but not described in the guide are simulated; they do not represent verified firmware screens.</p><p>Illustrative thermal model: heating at 2 °C/h, or 4 °C/h with Clim8zone, with proportional heat loss toward an ambient temperature of 22 °C. It does not calculate energy use or predict the behavior of a real spa. Settings are saved in this browser; devices, connections and readings restart when the page reloads.</p><div className="coverage-table"><table><thead><tr><th>Feature</th><th>Page</th><th>Fidelity</th><th>Details</th></tr></thead><tbody>{coverage.map(([name,page,level,detail])=><tr key={name}><td>{name}</td><td>{page}</td><td><span className={`fidelity ${level==='Documented'?'documented':''}`}>{level}</span></td><td>{detail}</td></tr>)}</tbody></table></div></div></details>
  </section>;
}
